import type { Roadmap, DocumentGroup } from "@/types";

const DISCLAIMER = "This information is for general educational purposes only and does not constitute legal advice. Immigration rules change frequently and individual circumstances vary. Please consult a licensed immigration attorney before filing any petitions or applications.";

function docGroups(groups: Record<string, string[]>): DocumentGroup[] {
  return Object.entries(groups).map(([category, items]) => ({ category, items }));
}

export const SCENARIO_ROADMAPS: Record<string, Roadmap> = {
  h1b_extension: {
    scenario: "H1B Extension",
    scenarioKey: "h1b_extension",
    summary: "You're extending your H1B status with your current employer. Your employer files Form I-129 on your behalf — you don't file anything yourself. The key is filing early: USCIS allows filing up to 6 months before your current status expires.",
    steps: [
      {
        order: 1,
        title: "Employer Gets a New Labor Condition Application (LCA)",
        formNumber: "ETA-9035",
        formName: "Labor Condition Application",
        fee: 0,
        processingTime: "~7 business days",
        processingWeeks: 1.5,
        description: "Your employer files an LCA with the Department of Labor certifying your wage and working conditions. This must be approved before the I-129 can be filed.",
        bullets: [
          "Filed by your employer's HR or immigration attorney — you don't need to do anything",
          "Takes about 7 business days if filed electronically",
          "Must cover the period of your H1B extension",
        ],
        documents: [],
        uscisLink: "https://flag.dol.gov/programs/LCA",
        whoFiles: "employer",
      },
      {
        order: 2,
        title: "Employer Files Form I-129 Petition",
        formNumber: "I-129",
        formName: "Petition for Nonimmigrant Worker",
        fee: 730,
        processingTime: "3–6 months",
        processingWeeks: 18,
        description: "The main petition your employer files to extend your H1B status. File at least 6 months before your current status expires. Optional premium processing (15 business days) costs an additional $2,805.",
        bullets: [
          "Your employer files this — you provide documents but don't sign the main petition",
          "File at least 6 months before expiration to preserve your status",
          "You're in valid status the entire time USCIS processes the petition",
        ],
        documents: [
          "Valid passport (6+ months validity beyond requested extension end date)",
          "Current I-94 printout (cbp.dhs.gov/I94)",
          "All previous H1B approval notices (I-797s)",
          "Copy of current LCA",
          "Degree certificates and official transcripts",
          "Pay stubs from last 3 months",
          "W-2 forms from last 2 years",
          "Employer support letter (title, salary, duties, start/end dates)",
        ],
        uscisLink: "https://www.uscis.gov/i-129",
        whoFiles: "employer",
      },
    ],
    documentGroups: docGroups({
      "Identity & Status": [
        "Valid passport (6+ months validity beyond requested end date)",
        "Current I-94 printout from cbp.dhs.gov/I94",
        "All previous H1B approval notices (I-797s)",
      ],
      "Employment Documents": [
        "Employer support letter (title, duties, salary, start/end dates)",
        "Pay stubs from last 3 months",
        "W-2 forms from last 2 years",
        "Copy of approved Labor Condition Application (LCA)",
      ],
      "Education Credentials": [
        "Degree certificate(s) — original or certified copy",
        "Official university transcripts",
        "Credential evaluation (if degree is from outside the US)",
      ],
    }),
    importantDeadlines: [
      "File at least 6 months before your current H1B expires",
      "LCA must be certified before I-129 is filed",
      "If using premium processing, pay the $2,805 fee at time of filing",
    ],
    disclaimer: DISCLAIMER,
  },

  h1b_transfer: {
    scenario: "H1B Employer Transfer",
    scenarioKey: "h1b_transfer",
    summary: "You're moving to a new employer while on H1B. Under H1B portability, you can legally start working for your new employer the day USCIS receives the petition — you don't need to wait for approval. Your existing cap slot carries over.",
    steps: [
      {
        order: 1,
        title: "New Employer Files LCA for New Position",
        formNumber: "ETA-9035",
        formName: "Labor Condition Application",
        fee: 0,
        processingTime: "~7 business days",
        processingWeeks: 1.5,
        description: "New employer gets a fresh LCA from the Department of Labor covering the new job title, salary, and location.",
        bullets: [
          "Must reflect the new job title, salary, and work location",
          "Typically takes 7 business days electronically",
          "Your new employer's attorney handles this",
        ],
        documents: [],
        uscisLink: "https://flag.dol.gov/programs/LCA",
        whoFiles: "employer",
      },
      {
        order: 2,
        title: "New Employer Files Transfer Petition",
        formNumber: "I-129",
        formName: "Petition for Nonimmigrant Worker (Transfer)",
        fee: 730,
        processingTime: "3–6 months",
        processingWeeks: 18,
        description: "Your new employer files I-129 with USCIS. Once USCIS receives it (not approves — receives), you can legally start your new job. Save the USCIS Receipt Notice as proof.",
        bullets: [
          "You may start working for the new employer on the date USCIS receives the petition",
          "Your current employer doesn't need to be notified or consent",
          "You don't re-enter the H1B lottery — your cap slot transfers",
        ],
        documents: [
          "Passport (valid for entire requested period)",
          "All previous H1B approval notices (I-797s from current and past employers)",
          "Current I-94 printout",
          "New employer's offer letter with title, salary, and job duties",
          "Degree certificates and transcripts",
          "Pay stubs from current employer (last 3 months)",
        ],
        uscisLink: "https://www.uscis.gov/i-129",
        whoFiles: "employer",
      },
    ],
    documentGroups: docGroups({
      "Identity & Status": [
        "Valid passport",
        "Current I-94 printout from cbp.dhs.gov/I94",
        "All previous H1B approval notices (I-797s from ALL past employers)",
      ],
      "New Employment": [
        "Offer letter from new employer (title, salary, duties, start date)",
        "Copy of new employer's LCA",
      ],
      "Current Employment": [
        "Pay stubs from current employer (last 3 months)",
        "W-2s from last 2 years",
      ],
      "Education Credentials": [
        "Degree certificate(s)",
        "Official transcripts",
        "Credential evaluation if foreign degree",
      ],
    }),
    importantDeadlines: [
      "Do NOT resign from current job until USCIS has received (not just approved) the new petition",
      "Get a screenshot or download of the online filing receipt the same day it's submitted",
      "Save the I-797C Receipt Notice as proof of authorization to work",
    ],
    disclaimer: DISCLAIMER,
  },

  h4_ead: {
    scenario: "H4 EAD (Work Authorization)",
    scenarioKey: "h4_ead",
    summary: "You're applying for an Employment Authorization Document as an H4 visa holder. The H4 EAD lets you work for any employer in the US — it's not tied to your spouse's employer. You're eligible because your spouse has an approved I-140.",
    steps: [
      {
        order: 1,
        title: "Confirm Eligibility: Spouse's I-140 Must Be Approved",
        formNumber: "I-140",
        formName: "Immigrant Petition for Alien Workers (spouse's)",
        fee: 0,
        processingTime: "Already filed by spouse's employer",
        processingWeeks: 0,
        description: "H4 EAD is only available if your spouse (the H1B holder) has an approved I-140 immigrant petition. This is a hard eligibility requirement — without it, you cannot file for EAD as an H4 holder.",
        bullets: [
          "Ask your spouse to provide a copy of their I-140 approval notice (I-797)",
          "The I-140 must be approved — pending is not enough",
          "Your spouse's employer typically has this on file",
        ],
        documents: [
          "Copy of spouse's I-140 approval notice (I-797)",
        ],
        uscisLink: "https://www.uscis.gov/i-140",
        whoFiles: "employer",
      },
      {
        order: 2,
        title: "File Form I-765 (EAD Application)",
        formNumber: "I-765",
        formName: "Application for Employment Authorization",
        fee: 520,
        processingTime: "3–5 months",
        processingWeeks: 18,
        description: "File under category (c)(26) — specifically for H4 holders with an approved I-140 in the family. You file this yourself (not your spouse's employer).",
        bullets: [
          "File under eligibility category (c)(26) on the form",
          "You may work for any employer once approved — not just your spouse's employer",
          "File concurrently with I-539 if your H4 status also needs to be extended",
        ],
        documents: [
          "Completed Form I-765",
          "Two passport-style photos (2\" x 2\")",
          "Copy of H4 visa stamp in passport",
          "Copy of current I-94 (yours, as H4 holder)",
          "Copy of H4 approval notice (I-797)",
          "Copy of spouse's H1B approval notice",
          "Copy of spouse's approved I-140 (I-797)",
          "Marriage certificate (with English translation if not in English)",
        ],
        uscisLink: "https://www.uscis.gov/i-765",
        whoFiles: "applicant",
      },
      {
        order: 3,
        title: "File Form I-539 If H4 Status Needs Extension",
        formNumber: "I-539",
        formName: "Application to Extend/Change Nonimmigrant Status",
        fee: 370,
        processingTime: "4–10 months",
        processingWeeks: 30,
        description: "If your H4 status is expiring, file I-539 to extend it. File concurrently with I-765 to save time. You can file both in the same envelope.",
        bullets: [
          "Only required if your H4 I-94 is expiring",
          "File at the same time as I-765 — USCIS processes them together",
          "You cannot work until the EAD card is received, regardless of I-539 status",
        ],
        documents: [
          "Completed Form I-539",
          "Copy of all current immigration documents (passport, I-94, H4 I-797)",
          "Copy of spouse's current H1B approval and I-94",
        ],
        uscisLink: "https://www.uscis.gov/i-539",
        whoFiles: "applicant",
      },
    ],
    documentGroups: docGroups({
      "Your Identity & H4 Status": [
        "Valid passport",
        "H4 visa stamp page (copy)",
        "Current I-94 printout (yours)",
        "H4 approval notice — I-797",
        "Two 2\"×2\" passport-style photos",
      ],
      "Spouse's H1B & I-140": [
        "Spouse's H1B approval notice (I-797)",
        "Spouse's approved I-140 approval notice (I-797)",
        "Spouse's current I-94 printout",
      ],
      "Relationship Evidence": [
        "Marriage certificate",
        "English translation of marriage certificate (if not in English)",
      ],
    }),
    importantDeadlines: [
      "File early — I-765 processing is 3–5 months and there's no premium processing",
      "File I-539 at the same time if your H4 is expiring within 6 months",
      "Do not work until you physically receive the EAD card",
    ],
    disclaimer: DISCLAIMER,
  },

  i485_aos: {
    scenario: "I-485 Adjustment of Status (Green Card)",
    scenarioKey: "i485_aos",
    summary: "You're applying for a green card while remaining in the US. Your I-140 is approved and your priority date is current, so you can file I-485 now. File I-765 (EAD) and I-131 (Advance Parole) at the same time — they're free when bundled with I-485.",
    steps: [
      {
        order: 1,
        title: "Confirm Priority Date is Current",
        formNumber: "Visa Bulletin",
        formName: "Monthly DOS Visa Bulletin",
        fee: 0,
        processingTime: "Check monthly",
        processingWeeks: 0,
        description: "Before filing I-485, your priority date (the date your I-140 was filed, or your labor cert date) must be 'current' in the monthly Visa Bulletin published by the State Department.",
        bullets: [
          "Check the Visa Bulletin at travel.state.gov each month",
          "Find your preference category (EB-2 or EB-3) and country of birth column",
          "Your priority date must be before the cutoff date shown — or the chart says 'C' (current)",
        ],
        documents: [],
        uscisLink: "https://travel.state.gov/content/travel/en/legal/visa-law0/visa-bulletin.html",
        whoFiles: "applicant",
      },
      {
        order: 2,
        title: "Complete I-693 Medical Exam",
        formNumber: "I-693",
        formName: "Report of Medical Examination and Vaccination Record",
        fee: 200,
        processingTime: "Same day (schedule in advance)",
        processingWeeks: 0.5,
        description: "A USCIS-designated civil surgeon must complete your medical exam. The sealed envelope from the civil surgeon goes directly into your I-485 package — do not open it.",
        bullets: [
          "Find a civil surgeon at uscis.gov/civil-surgeons",
          "Bring your vaccination records — you may need catch-up shots",
          "The exam result is valid for 2 years",
        ],
        documents: [
          "Government-issued photo ID",
          "Vaccination records (immunization history)",
          "Payment for civil surgeon fee (~$200–$500, varies by doctor)",
        ],
        uscisLink: "https://www.uscis.gov/i-693",
        whoFiles: "applicant",
      },
      {
        order: 3,
        title: "File I-485 + I-765 + I-131 Bundle",
        formNumber: "I-485",
        formName: "Application to Register Permanent Residence",
        fee: 1440,
        processingTime: "8–24 months",
        processingWeeks: 60,
        description: "The main green card application. File I-765 (EAD to work while pending) and I-131 (Advance Parole to travel while pending) in the same package — they're free when filed with I-485. Do not miss I-131 — traveling without it abandons your I-485.",
        bullets: [
          "File all three forms (I-485, I-765, I-131) together in one package",
          "The $1,440 fee covers all three — I-765 and I-131 are free when bundled",
          "USCIS will send a biometrics appointment within 3–4 months",
        ],
        documents: [
          "Completed I-485, I-765 (category (c)(9)), and I-131",
          "Valid passport",
          "All prior visa approval notices (I-797s)",
          "Current I-94",
          "Approved I-140 approval notice",
          "Birth certificate with English translation",
          "Marriage certificate (if applicable) with translation",
          "Two passport-style photos",
          "Sealed I-693 medical exam envelope from civil surgeon",
          "Tax returns last 3 years + W-2s",
          "Pay stubs last 3 months",
          "Evidence of continuous lawful status",
          "Police clearance certificates (for countries where you lived 6+ months after age 16)",
        ],
        uscisLink: "https://www.uscis.gov/i-485",
        whoFiles: "applicant",
      },
      {
        order: 4,
        title: "Attend Biometrics Appointment",
        formNumber: "ASC Appointment",
        formName: "Biometrics (Fingerprints + Photos)",
        fee: 0,
        processingTime: "Scheduled by USCIS (~3–4 months after filing)",
        processingWeeks: 16,
        description: "USCIS will mail you an appointment notice for a local Application Support Center. You'll provide fingerprints, photos, and a signature. Bring the notice + a government ID.",
        bullets: [
          "USCIS mails the appointment — watch for it",
          "Bring the ASC appointment notice and a valid photo ID",
          "Takes about 30 minutes — no preparation needed",
        ],
        documents: [
          "ASC appointment notice (Form I-797C)",
          "Government-issued photo ID (passport or driver's license)",
        ],
        uscisLink: "https://www.uscis.gov/i-485",
        whoFiles: "applicant",
      },
      {
        order: 5,
        title: "USCIS Interview (If Required)",
        formNumber: "Interview",
        formName: "Adjustment of Status Interview",
        fee: 0,
        processingTime: "6–18 months after filing",
        processingWeeks: 52,
        description: "Many employment-based I-485s are approved without an interview, but USCIS may schedule one. If required, you'll attend at your local field office. Your attorney should accompany you.",
        bullets: [
          "Not all cases require an interview — USCIS will notify you if one is needed",
          "Bring originals of all documents submitted with your I-485",
          "Answer questions about your application honestly and consistently",
        ],
        documents: [
          "Original passport",
          "Original birth certificate",
          "Original I-140 approval notice",
          "All tax returns and supporting documents",
          "Any RFE responses if applicable",
        ],
        uscisLink: "https://www.uscis.gov/green-card/green-card-processes-and-procedures",
        whoFiles: "applicant",
      },
    ],
    documentGroups: docGroups({
      "Identity Documents": [
        "Valid passport",
        "Birth certificate with English translation",
        "Marriage certificate + translation (if applicable)",
        "Two 2\"×2\" passport-style photos",
      ],
      "Immigration History": [
        "All prior visa approval notices (I-797s)",
        "Current I-94 printout",
        "Approved I-140 approval notice",
        "Evidence of continuous lawful status in US",
      ],
      "Medical": [
        "Completed I-693 medical exam (sealed envelope from civil surgeon)",
        "Vaccination records",
      ],
      "Financial Documents": [
        "Tax returns — last 3 years (1040 + all schedules)",
        "W-2s — last 2 years",
        "Pay stubs — last 3 months",
        "Bank statements — last 3 months (optional but helpful)",
      ],
      "Background & History": [
        "Police clearance certificates (for every country lived in 6+ months after age 16, excluding US)",
        "Court/arrest records (if any) with certified translations",
      ],
    }),
    importantDeadlines: [
      "Check the Visa Bulletin each month — file immediately when your priority date becomes current",
      "File I-131 (Advance Parole) WITH your I-485 — do not travel internationally until you receive AP",
      "I-693 medical exam is valid for 2 years — schedule it close to filing date",
      "Respond to any USCIS RFE (Request for Evidence) within the deadline stated in the notice",
    ],
    disclaimer: DISCLAIMER,
  },
};
